export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  PRODUCTS: '/products',
  PRODUCT_DETAILS: '/products/:id',
  CROP_SOLUTIONS: '/crop-solutions',
  INNOVATION: '/innovation',
  DEALER_NETWORK: '/dealer-network',
  KNOWLEDGE_CENTER: '/knowledge-center',
  BLOGS: '/blogs',
  BLOG_DETAILS: '/blogs/:id',
  CAREERS: '/careers',
  CONTACT: '/contact',
  GALLERY: '/gallery',
  FAQ: '/faq',
  ADMIN_DASHBOARD: '/admin',
  DEALER_PORTAL: '/dealer-portal',
  NOT_FOUND: '*',
};
